spring:
  application:
    name: assignment
  main:
    # the following will disable the SPRING ascii-art in the logfile on server startup
    show_banner: false
server:
  address: 127.0.0.1
  port: 9090

mongoDb:
  dbName: dummy
  serverList:
    server1:
      host: 127.0.0.1
      port: 27017